from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

HOST = "127.0.0.1"
PORT = 8020
PLUGIN_DIR = Path(__file__).resolve().parents[1]
FACE_WIDTH = 36
FACE_HEIGHT = 36
FACE_CHANNELS = 3
METRIC_INTERVAL_SECONDS = 0.45
INPUT_FPS_WINDOW_SECONDS = 3.0
MODEL_INPUT_TARGET_FPS = 15
MJPEG_STREAM_FPS = 20
MJPEG_CACHE_SECONDS = 1.0 / MJPEG_STREAM_FPS
PREVIEW_JPEG_QUALITY = 74
HR_WINDOW_SECONDS = 10
WAVEFORM_SAMPLE_LIMIT = 300
MAX_CLIENT_TS_GAP_SECONDS = 1.5
OUTPUT_SQI_THRESHOLD = 0.38
PREVIEW_SQI_THRESHOLD = 0.2
OUTPUT_TTL_SECONDS = 3.0
DEVICE_SCAN_MAX = 5
CAPTURE_NO_FRAME_TIMEOUT_SECONDS = 2.0
DEFAULT_CAPTURE = {"device_index": 0, "width": 1280, "height": 720, "fps": 30}
MJPEG_BOUNDARY = "live-heart-frame"
MAX_UPLOAD_BYTES = 512 * 1024 * 1024
UPLOAD_CHUNK_BYTES = 1024 * 1024
VIDEO_EXTENSIONS = {".mp4", ".mov", ".m4v", ".avi", ".mkv", ".webm"}
AGENT_DEFAULT_BASE_URL = ""
AGENT_DEFAULT_AUTH_TOKEN = ""
AGENT_DEFAULT_API_KEY = ""
AGENT_DEFAULT_PROTOCOL = "anthropic"
AGENT_DEFAULT_MODEL = "bedrock-claude-haiku"
AGENT_DEFAULT_VERSION = "2023-06-01"
AGENT_LOCAL_CONFIG_PATH = PLUGIN_DIR / "agent_config.local.json"
AGENT_LOG_DIR = PLUGIN_DIR / "agent_logs"
AGENT_HISTORY_LIMIT = 24
AGENT_RECENT_HEART_SECONDS = 90
AGENT_AUTO_COOLDOWN_SECONDS = 45.0
AGENT_BPM_DELTA_TRIGGER = 8.0
AGENT_HTTP_TIMEOUT_SECONDS = 30.0
AGENT_SUBTITLE_TTL_SECONDS = 18.0
AGENT_MAX_USER_TEXT_CHARS = 800
AGENT_MAX_REPLY_CHARS = 1400
AGENT_MAX_SUBTITLE_CHARS = 64
RECORDINGS_DIR = PLUGIN_DIR / "recordings"
RECORDING_EXPORTS_DIR = RECORDINGS_DIR / "exports"
HIGHLIGHT_CLIP_SECONDS = 30.0
HIGHLIGHT_HALF_SECONDS = HIGHLIGHT_CLIP_SECONDS / 2.0
HIGHLIGHT_MIN_CLIP_SECONDS = 20.0
HIGHLIGHT_MAX_CLIP_SECONDS = 45.0
HIGHLIGHT_PRE_ROLL_SECONDS = 8.0
HIGHLIGHT_POST_ROLL_SECONDS = 12.0
HIGHLIGHT_MIN_SAMPLES = 8
HIGHLIGHT_MAX_SAMPLE_GAP_SECONDS = 6.0
HIGHLIGHT_LIMIT = 5
HIGHLIGHT_OVERLAP_RATIO = 0.5
HIGHLIGHT_MIN_HR = 30.0
HIGHLIGHT_MAX_HR = 180.0
HIGHLIGHT_MIN_DELTA_HR = 5.0
HIGHLIGHT_BASELINE_MIN_AGE_SECONDS = 20.0
HIGHLIGHT_BASELINE_MAX_AGE_SECONDS = 120.0
HIGHLIGHT_TRIGGER_PROMINENCE_HR = 5.0
HIGHLIGHT_TRIGGER_RISE_10S = 4.0
HIGHLIGHT_STRONG_PROMINENCE_HR = 8.0
HIGHLIGHT_EXIT_PROMINENCE_HR = 3.0
HIGHLIGHT_EXIT_SECONDS = 8.0
HIGHLIGHT_MIN_COVERAGE = 0.7
HIGHLIGHT_MERGE_GAP_SECONDS = 12.0
HIGHLIGHT_EMA_ALPHA = 0.35
HIGHLIGHT_MAX_SMOOTH_JUMP_PER_SECOND = 5.0
